### ISSUE TITLE
Player Module

### ISSUE THREAD

**Issue by addictgamer** [TurningWheel/Barony#29]
# Overview

_**Description:**_ Create a Player class and use it to track all of a player's relevant data.

_**End-goal:**_ support split-screen couch or console play.

###  Task list

**Preliminary work**
 - [x] ~~Convert `players` array from Entity pointers to the `Player` class type.~~ *Available on the gamepad branch*
 - [x] ~~Player instances track their Entity.~~ *Available on the gamepad branch*

**Graphics-related**
 - [ ] Each Player instance should somehow render itself to the screen (every player gets its own `SDL_Surface *screen;`?)

**Input & Control:**
 - [ ] `keystatus[]` and `inputPressed()` should be integrated into the Player class.
 - [ ] Each Player instance keeps track of its keybindings/gamepad bindings
 - [ ] Each Player instance has its own input method (controller & keyboard, gamepads, etc)

**Misc:**
 - [ ] Player instances store and retrieve their own settings from a corresponding player<#>.cfg. (Graphics settings, keybindings, etc)
 - [ ] All of the required menus and GUI changes this work necessitates.

*Note: This list is not complete, more is to come. Questions, comments, and suggestions welcome.*
